apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: docker.io/library/img-2023mt03533:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_VERSION
            - name: APP_TITLE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_TITLE
